apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Increased size for Kafka logs
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kafka"
