# mysql-statefulset.yaml

# Headless Service (无需改动)
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
# StatefulSet for the MySQL server
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "newTik"
          volumeMounts:
            # 这个名字必须和下面 volumes 定义的 name 一致
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      # ===================== 关键改动在这里 =====================
      # 1. 移除了原来的 volumeClaimTemplates 部分
      # 2. 添加了下面的 volumes 部分
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            # 明确指定使用我们之前创建的名为 mysql-pvc 的 PVC
            claimName: mysql-pvc
      # =========================================================