# Headless Service for the Redis StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
  # A headless service is required for the StatefulSet.
  clusterIP: None
---
# StatefulSet for the Redis server
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          # Use a command to start Redis with append-only file persistence enabled.
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-persistent-storage
              # Mount the persistent volume at the location where Redis stores its data.
              mountPath: /data
  # volumeClaimTemplates create a dedicated PVC for each Redis pod.
  volumeClaimTemplates:
    - metadata:
        name: redis-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 256Mi
