# Service Port
port: "50051"

# Log Level (debug, info, warn, error)
log_level: "info"

# Database Configuration (DSN)
database:
  dsn: "root:123456@tcp(127.0.0.1:3306)/newTik?charset=utf8mb4&parseTime=True&loc=Local"

# Redis Configuration
redis:
  address: "127.0.0.1:6379"
  password: "" # no password set
  db: 0 # default DB
