# --- 第 1 部分：为用户服务创建 ConfigMap ---
# 最佳实践：将配置与应用代码分离
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  MYSQL_DSN: "user:password@tcp(mysql-service:3306)/userdb?parseTime=true"
  PORT: "50051"
---
# --- 第 2 部分：修改后的 Deployment ---
# 添加了 envFrom 来从 ConfigMap 注入环境变量
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
              name: grpc

          # --- 新增部分：从 ConfigMap 注入环境变量 ---
          envFrom:
            - configMapRef:
                # 引用上面定义的 ConfigMap 的名称
                name: user-service-config
---
# --- 第 3 部分：原有的 Service 定义 ---
# 无需改动
apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    konghq.com/protocol: grpc
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: grpc
      protocol: TCP
      appProtocol: grpc
      port: 50051
      targetPort: 50051