
_format_version: "3.0"
services:
- name: example-service
  url: http://httpbin.org/anything
  routes:
  - name: example-route
    paths:
    - /example

# --- User Service (gRPC) ---
- name: user-service
  # Kong 的 Service 指向 Kubernetes 的 Service
  # .default.svc.cluster.local 是 k8s 内部的 DNS 名称
  url: grpc://user-service.default.svc.cluster.local:50051
  routes:
  - name: user-service-route
    paths:
    # 我们将所有 /users 的请求都路由到 user-service
    - /users
    strip_path: true
    plugins:
    # 使用 grpc-gateway 插件进行协议转换
    - name: grpc-gateway
      config:
        # 将 proto descriptor 的内容直接以 base64 编码形式嵌入
        proto: "Cv8BCh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvEg9nb29nbGUucHJvdG9idWYiOwoJVGltZXN0YW1wEhgKB3NlY29uZHMYASABKANSB3NlY29uZHMSFAoFbmFub3MYAiABKAVSBW5hbm9zQoUBChNjb20uZ29vZ2xlLnByb3RvYnVmQg5UaW1lc3RhbXBQcm90b1ABWjJnb29nbGUuZ29sYW5nLm9yZy9wcm90b2J1Zi90eXBlcy9rbm93bi90aW1lc3RhbXBwYvgBAaICA0dQQqoCHkdvb2dsZS5Qcm90b2J1Zi5XZWxsS25vd25UeXBlc2IGcHJvdG8zCr4BChtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8SD2dvb2dsZS5wcm90b2J1ZiIHCgVFbXB0eUJ9ChNjb20uZ29vZ2xlLnByb3RvYnVmQgpFbXB0eVByb3RvUAFaLmdvb2dsZS5nb2xhbmcub3JnL3Byb3RvYnVmL3R5cGVzL2tub3duL2VtcHR5cGL4AQGiAgNHUEKqAh5Hb29nbGUuUHJvdG9idWYuV2VsbEtub3duVHlwZXNiBnByb3RvMwqSCAoXYXBpL3Byb3RvL3YxL3VzZXIucHJvdG8SB3VzZXJfdjEaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8aG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90byKLAwoEVXNlchISCgR1dWlkGAEgASgJUgR1dWlkEhIKBG5hbWUYAiABKAlSBG5hbWUSEAoDYWdlGAMgASgNUgNhZ2USFgoGZ2VuZGVyGAQgASgNUgZnZW5kZXISJwoPZm9sbG93aW5nX2NvdW50GAUgASgEUg5mb2xsb3dpbmdDb3VudBIlCg5mb2xsb3dlcl9jb3VudBgGIAEoBFINZm9sbG93ZXJDb3VudBIlCg50b3RhbF9mYXZvcml0ZRgHIAEoBFINdG90YWxGYXZvcml0ZRIdCgp3b3JrX2NvdW50GAggASgEUgl3b3JrQ291bnQSJQoOZmF2b3JpdGVfY291bnQYCSABKARSDWZhdm9yaXRlQ291bnQSOQoKY3JlYXRlZF9hdBgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBSCWNyZWF0ZWRBdBI5Cgp1cGRhdGVkX2F0GAsgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcFIJdXBkYXRlZEF0IoIBChFDcmVhdGVVc2VyUmVxdWVzdBISCgR1dWlkGAEgASgJUgR1dWlkEhIKBG5hbWUYAiABKAlSBG5hbWUSFQoDYWdlGAMgASgNSABSA2FnZYgBARIbCgZnZW5kZXIYBCABKA1IAVIGZ2VuZGVyiAEBQgYKBF9hZ2VCCQoHX2dlbmRlciJlChFVcGRhdGVVc2VyUmVxdWVzdBISCgR1dWlkGAEgASgJUgR1dWlkEhIKBG5hbWUYAiABKAlSBG5hbWUSEAoDYWdlGAMgASgNUgNhZ2USFgoGZ2VuZGVyGAQgASgNUgZnZW5kZXIiLwoZR2V0VXNlckluZm9ybWF0aW9uUmVxdWVzdBISCgR1dWlkGAEgASgJUgR1dWlkMtoBCgtVc2VyU2VydmljZRJACgpDcmVhdGVVc2VyEhoudXNlcl92MS5DcmVhdGVVc2VyUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRJACgpVcGRhdGVVc2VyEhoudXNlcl92MS5VcGRhdGVVc2VyUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRJHChJHZXRVc2VySW5mb3JtYXRpb24SIi51c2VyX3YxLkdldFVzZXJJbmZvcm1hdGlvblJlcXVlc3QaDS51c2VyX3YxLlVzZXJCIFoeL2ludGVybmFsL2NvbW1vbi9nZW5wcm90by91c2VyYgZwcm90bzM="
