
_format_version: "3.0"
services:
- name: example-service
  url: http://httpbin.org/anything
  routes:
  - name: example-route
    paths:
    - /example

# --- User Service (gRPC) ---
- name: user-service
  url: grpc://user-service.default.svc.cluster.local:50051
  routes:
  - name: user-service-route
    paths:
    - /users
    strip_path: true
    plugins:
    - name: grpc-gateway
      config:
        # 通过绝对路径引用容器内的 .proto 源文件
        proto: /kong_config/user.proto
