
image:
  repository: kong/kong-gateway
  tag: "3.9"

env:
  database: "off"
  # 告诉 Kong 在哪里找到它的声明式配置文件
  declarative_config: /kong_config/kong.yaml

# 使用 userDefinedVolumes 将我们手动创建的 ConfigMap 挂载到 Kong Pod 中
# 这是最明确、最可靠的挂载方式
userDefinedVolumes:
  - name: kong-declarative-config-volume
    configMap:
      name: kong-declarative-config

userDefinedVolumeMounts:
  - name: kong-declarative-config-volume
    mountPath: /kong_config

# --- 以下配置保持不变 ---
ingressController:
  enabled: false

proxy:
  type: LoadBalancer
  http:
    enabled: true
    port: 80

admin:
  enabled: false

manager:
  enabled: false
